Update agot_battlefield_duels_l_german.yml
Dillo234/AGOT-Deutsch pull request #45
Opened 2023-04-21 14:39 UTC by GilianTorhammer

2023-04-21 20:36 UTC, Dillo234 requested changes
Bitte lies, was du übersetzt, und lass nicht alles DeepL machen.
Nur doppelte Arbeit.

2023-04-23 10:09 UTC, TempoTaschentuch approved these changes
Das \n\n wurde in Zeile 13 entfernt.
Ich habe es wieder hinzugefügt

"...meines Feindes ausgeliefert.**_\n\n_**[sc_victor.GetTitledFirstName] hebt..."

2023-04-23 10:25 UTC, TempoTaschentuch approved these changes
ups

hab grad was probiert :P

2023-04-23 15:59 UTC, mijnders approved these changes

2023-04-23 16:04 UTC, merged